### ISSUE TITLE
Servicio dejó de funcionar

### ISSUE THREAD

**Issue by felipecastilla** [sagmor/sii_chile#14]
Desde hace un tiempo el servicio dejó de funcionar y manda un error de Heroku

**Comment by sagmor** [comment]
Heroku dejo de proveer su servicio gratuito (lo que explica que el servicio haya dejado de funcionar)

Estoy buscando una solución y espero poder reponer el servicio pronto 👍

**Comment by sagmor** [comment]
Acabo de reactivar mi cuenta de Heroku para mantener la API operando.

Esto tiene un costo que planeo pagar por ahora, pero active el sistema de sponsorships por si quieren aportar al funcionamiento del servicio.

https://github.com/sponsors/sagmor

**Comment by thxare** [comment]
Hola, ya no está funcionando?

**Comment by Theblood** [comment]
Al final lo levante en una maquina free.. https://sii.alwaysdata.net/consulta?rut=76.118.195-5  al menos funciona
