### ISSUE TITLE
gema de ruby: "getaddrinfo: Name or service not known"

### ISSUE THREAD

**Issue by holic-cl** [sagmor/sii_chile#2]
Hola!, lo probé en ruby pero me sale esto:
irb(main):004:0> SIIChile::Consulta.new('76.118.195-5').resultado
=> {:rut=>"76.118.195-5", :error=>"getaddrinfo: Name or service not known"}

¿ya no funciona?

**Comment by crisnowz** [comment]
Tengo el mismo problema, pero lo he probado de 2 celulares diferente con su internet propia y además el de mi oficina y arroja el mismo error ! 

http://siichile.herokuapp.com/consulta?rut=76.475.735-1
