### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by benytocarlo** [sagmor/sii_chile#4]
Hola Seba!, estoy trabajando en un proyecto de startup chile y me gustaría saber si existe alguna gema como la que desarrollaste para SII pero para Colombia o otro pais de latino america?

**Comment by sagmor** [comment]
No tengo la menor idea :stuck_out_tongue_closed_eyes: 

la verdad no se como funcionan los "SIIs" del resto de latinoamerica tampoco, pero podrías usar esta gema como base para otros países, si tienes dudas de como funciona me puedes preguntar :wink:
