### ISSUE TITLE
Acceso a DTEs

### ISSUE THREAD

**Issue by mantoniocc** [sagmor/sii_chile#5]
Hola Seba como estas?
Sabes si es posible que el SII tenga algún API para acceder a los DTEs o por lo menos a las facturas de venta y compra. He visto que hoy en día algunas aplicaciones o emprendimiento que se están realizando capturan dicha información.  Existe la documentación para crear un sistema de facturación electrónica de hecho la he leído, pero no aparece nada como esto.
Saludos

**Comment by sagmor** [comment]
A que te refieres con acceder a los DTEs?

La API de generación de documentos es en base a XMLs y no he jugado con ella directamente.
Lo que mas se es de una [implementación en Java de Niclabs](https://github.com/niclabs/DTE)
