### ISSUE TITLE
Algunas consultas retornan un error

### ISSUE THREAD

**Issue by tikoflano** [sagmor/sii_chile#7]
Esta consulta funciona correctamente:

[https://siichile.herokuapp.com/consulta?rut=760700894](https://siichile.herokuapp.com/consulta?rut=760700894)

Mientras que esta (y muchas otras, la mayoria diria yo) tiran un error:

[https://siichile.herokuapp.com/consulta?rut=124868645](https://siichile.herokuapp.com/consulta?rut=124868645)

El error que se obtiene es

`{"rut":"12.486.864-5","error":"SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed"}`

Los RUT con los que he probado antes funcionaban correctamente.

**Comment by diegoshock** [comment]
esto a dia de hoy funcionará?

**Comment by sagmor** [comment]
veo que funciona

**Comment by diegoshock** [comment]
????
